{% set name = "ipydatawidgets" %}
{% set version = "4.3.4" %}
{% set sha256 = "124c0fc7b10e2d1ad5c20942f3e5a7e6c28cc8283f1e1bb7283a2d0ee55832d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - jupyter-packaging
    - jupyterlab >=3,<4
    - nodejs
    - yarn
  run:
    - python >=3.7
    - ipywidgets >=7,<9
    - numpy
    - traittypes >=0.2

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/vidartf/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A set of widgets to help facilitate reuse of large datasets across widgets

extra:
  recipe-maintainers:
    - vidartf
    - jasongrout
